name: Continuous Integration on Pull Request

on:
  pull_request:

jobs:
  php-cs-fixer:
    name: PHP Coding Standards Fixer on ${{ matrix.operating-system }})
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '8.1' ]

    runs-on: ubuntu-latest
    steps:
      # —— Github Checkout 🔎 ——————————————————————————————————————————————————
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # —— Setup php —————————————————————————————————————————————————————————
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: php-cs-fixer

      # —— php-cs-fixer ——————————————————————————————————————————————————————
      - name: Run php-cs-fixer
        run: php-cs-fixer fix --dry-run -v

  symfony:
    name: Symfony ${{ matrix.symfony }} (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    needs: php-cs-fixer
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [ '7.4', '8.0', '8.1' ]
        symfony: [ '5.4', '6.0' ]
        exclude:
          - php-versions: '7.4'
            symfony: '6.0'

    runs-on: ${{ matrix.operating-system }}

    steps:
        # —— Git Checkout PR branch ——————————————————————————————————————————
      - name: Git Checkout PR branch (${{ github.ref }})
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # —— Setup php —————————————————————————————————————————————————————————
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        env:
          COMPOSER_AUTH: "${{ secrets.COMPOSER_AUTH }}"
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          tools: composer:v2

      # —— Composer cache ————————————————————————————————————————————————————
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # —— Install composer dependencies —————————————————————————————————————
      - name: Install Composer dependencies
        env:
          COMPOSER_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          composer global require --no-interaction --no-progress symfony/flex:^1.11
          composer config extra.symfony.require "${{ matrix.symfony }}.*"
          composer install --no-progress --no-scripts -q

#      # —— PHPStan  ——————————————————————————————————————————————————————————
#      - name: PHPStan (PHP Static Analysis)
#        run: php vendor/phpstan/phpstan/phpstan.phar --memory-limit=1G

      # —— Run tests —————————————————————————————————————————————————————————
      - name: Run Tests
        run: php vendor/bin/phpunit
